<h2>Complex handling</h2>
<p></p><p>There is a function <code class="java">suspiciousFunction</code>, and for some reason, you suspect that an exception might occur in it.</p><p>Process the call of <code class="java">suspiciousFunction</code> with the help of the <code class="java">try-catch-finally</code> statement. If an exception occurs in the function, print the exception message. </p><p>In the case of <code class="java">IOException</code>, print the following message instead: <code class="java">The IOException occurred</code>.</p><p>In the final block, output <code class="java">Handling completed successfully!</code>.</p><p><button class="btn-sm btn-outline-secondary" onclick="getElementById('hint-564').style.display='inline'">
        Hint
      </button>
</p><div id="hint-564" style="display:none;"> Use <code class="java">message</code> to get information about the exception. </div><br><br><font color="gray">Memory limit: 256 MB</font><br><font color="gray">Time limit: 8 seconds</font><br><br>
<b>Caution</b><br><br>
You may see errors in your code or execution results due to missing context. Donâ€™t worry about it, just write the solution and press Check.
<br><br>
